### ISSUE TITLE
Check from DevØps

### ISSUE THREAD

**Issue by Islex** [DEV-OPS-Group-b/new-mini-twit-web-app#3]
We have checked if the system is working as the original Mini-twit application, and came with the following comments:
  Do you see a public timeline? - Yes
  Does the public timeline show messages that the application received from the simulator?
	  - No I don't see any messages from the simulator? 
  Can you create a new user? - Yes, I was able to do that.
  Can you login as a new user? - Yes.
  Can you write a message? Yes, but it does not show up when I publish it.
  After publishing a message, does it appear on you private timeline? - No.
  Can you follow another user? - No, since I cannot see other users.

**Comment by Diiiya** [comment]
Issues should be fixed now
